-- Bakeshop Weather v0.5 production schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'viewer' check (role in ('admin','manager','viewer')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.branches (
  id uuid primary key default gen_random_uuid(), branch_name text not null, address text,
  latitude double precision not null check (latitude between -90 and 90), longitude double precision not null check (longitude between -180 and 180),
  timezone text not null default 'Asia/Manila', is_active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.weather_forecasts (
  id bigint generated by default as identity primary key, branch_id uuid not null references public.branches(id) on delete cascade,
  forecast_run_time timestamptz not null, forecast_time timestamptz not null, temperature_c numeric(5,2), apparent_temperature_c numeric(5,2),
  humidity_pct integer, rain_probability_pct integer, precipitation_mm numeric(7,2), rain_mm numeric(7,2), weather_code integer,
  cloud_cover_pct integer, wind_speed_kmh numeric(7,2), wind_direction_deg integer, visibility_m integer,
  source text not null default 'open-meteo', provider_model text, provider_timezone text, created_at timestamptz not null default now(),
  unique(branch_id, forecast_run_time, forecast_time, source)
);
create table if not exists public.weather_observations (
  id bigint generated by default as identity primary key, branch_id uuid not null references public.branches(id) on delete cascade,
  observation_time timestamptz not null, did_rain boolean not null, rain_intensity text, actual_temperature_c numeric(5,2), notes text,
  verified_by uuid references auth.users(id) on delete set null, verified_at timestamptz not null default now(), created_at timestamptz not null default now()
);
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key, actor_id uuid references auth.users(id) on delete set null,
  action text not null, entity_type text not null, entity_id text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create index if not exists weather_forecasts_branch_time_idx on public.weather_forecasts(branch_id, forecast_time);
create index if not exists weather_forecasts_run_idx on public.weather_forecasts(branch_id, forecast_run_time);
create index if not exists weather_observations_branch_time_idx on public.weather_observations(branch_id, observation_time);
create index if not exists audit_logs_created_idx on public.audit_logs(created_at desc);

alter table public.profiles enable row level security; alter table public.branches enable row level security; alter table public.weather_forecasts enable row level security; alter table public.weather_observations enable row level security; alter table public.audit_logs enable row level security;

drop policy if exists "profiles own read" on public.profiles;
create policy "profiles own read" on public.profiles for select to authenticated using (id = auth.uid());
drop policy if exists "authenticated can read branches" on public.branches;
create policy "authenticated can read branches" on public.branches for select to authenticated using (true);
drop policy if exists "managers can manage branches" on public.branches;
create policy "managers can manage branches" on public.branches for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','manager') and p.is_active)) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','manager') and p.is_active));
drop policy if exists "authenticated can read forecasts" on public.weather_forecasts;
create policy "authenticated can read forecasts" on public.weather_forecasts for select to authenticated using (true);
drop policy if exists "managers can manage forecasts" on public.weather_forecasts;
create policy "managers can manage forecasts" on public.weather_forecasts for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','manager') and p.is_active)) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','manager') and p.is_active));
drop policy if exists "authenticated can read observations" on public.weather_observations;
create policy "authenticated can read observations" on public.weather_observations for select to authenticated using (true);
drop policy if exists "managers can manage observations" on public.weather_observations;
create policy "managers can manage observations" on public.weather_observations for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','manager') and p.is_active)) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','manager') and p.is_active));
drop policy if exists "admins can read audit logs" on public.audit_logs;
create policy "admins can read audit logs" on public.audit_logs for select to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin' and p.is_active));

-- Admin user management can invite users through the backend service-role API; profiles are created automatically.


-- v0.6 source metadata / operational indexes
alter table public.weather_forecasts add column if not exists provider_model text;
alter table public.weather_forecasts add column if not exists provider_timezone text;
create index if not exists branches_active_idx on public.branches(is_active, branch_name);

-- v1.1 persistent operational alert history
create table if not exists public.weather_alerts (
  id bigint generated by default as identity primary key,
  branch_id uuid not null references public.branches(id) on delete cascade,
  alert_key text not null,
  severity text not null check (severity in ('watch','high')),
  threshold_pct integer not null default 50,
  peak_probability_pct integer not null,
  peak_time timestamptz not null,
  window_start timestamptz not null,
  window_end timestamptz not null,
  source text not null default 'open-meteo',
  status text not null default 'open' check (status in ('open','cleared')),
  detected_at timestamptz not null default now(),
  cleared_at timestamptz,
  last_seen_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique(branch_id, alert_key, window_start)
);
create index if not exists weather_alerts_status_idx on public.weather_alerts(status, severity, last_seen_at desc);
create index if not exists weather_alerts_branch_idx on public.weather_alerts(branch_id, detected_at desc);
alter table public.weather_alerts enable row level security;
drop policy if exists "authenticated can read weather alerts" on public.weather_alerts;
create policy "authenticated can read weather alerts" on public.weather_alerts for select to authenticated using (true);
drop policy if exists "managers can manage weather alerts" on public.weather_alerts;
create policy "managers can manage weather alerts" on public.weather_alerts for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','manager') and p.is_active)) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','manager') and p.is_active));
